# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Watcharanon Kerdkaew\PycharmProjects\MyGuiProjestCPE\DesignGui\Optionpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#---------------------- Connection Database Mysql ---------------------------#
import mysql.connector
cnx = mysql.connector.connect(host="localhost", user="root1", password="123456789", database="wprojectcpe62")       # connect to MySql database
cur = cnx.cursor()
#----------------------------------------------------------------------------#

from PyQt5 import QtCore, QtGui, QtWidgets
from subprocess import call

class Ui_OptionPage(object):
    def setupUi(self, OptionPage):
        OptionPage.setObjectName("OptionPage")
        OptionPage.resize(1280, 800)
        OptionPage.showFullScreen()
        OptionPage.setStyleSheet("#OptionPage{background-color: rgb(178, 201, 255);}")
        self.centralwidget = QtWidgets.QWidget(OptionPage)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Undo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Undo.setGeometry(QtCore.QRect(30, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Undo.setFont(font)
        self.pushButton_Undo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_Undo.setStyleSheet("background-color: rgb(255, 51, 51);\n"
"")
        self.pushButton_Undo.setObjectName("pushButton_Undo")
        self.label_Restart = QtWidgets.QLabel(self.centralwidget)
        self.label_Restart.setGeometry(QtCore.QRect(580, 460, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Restart.setFont(font)
        self.label_Restart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Restart.setObjectName("label_Restart")
        self.label_Power = QtWidgets.QLabel(self.centralwidget)
        self.label_Power.setGeometry(QtCore.QRect(280, 460, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Power.setFont(font)
        self.label_Power.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Power.setObjectName("label_Power")
        self.pushButton_ExitProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ExitProgram.setGeometry(QtCore.QRect(790, 180, 300, 300))
        self.pushButton_ExitProgram.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_ExitProgram.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/pi/Desktop/New folder/MyGuiProjestCPE/GuiPythonCode/Image/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ExitProgram.setIcon(icon)
        self.pushButton_ExitProgram.setIconSize(QtCore.QSize(190, 190))
        self.pushButton_ExitProgram.setFlat(True)
        self.pushButton_ExitProgram.setObjectName("pushButton_ExitProgram")
        self.label_ExitProgram = QtWidgets.QLabel(self.centralwidget)
        self.label_ExitProgram.setGeometry(QtCore.QRect(850, 460, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_ExitProgram.setFont(font)
        self.label_ExitProgram.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ExitProgram.setObjectName("label_ExitProgram")
        self.pushButton_Power = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Power.setGeometry(QtCore.QRect(180, 180, 300, 300))
        self.pushButton_Power.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_Power.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/pi/Desktop/New folder/MyGuiProjestCPE/GuiPythonCode/Image/power_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Power.setIcon(icon1)
        self.pushButton_Power.setIconSize(QtCore.QSize(190, 190))
        self.pushButton_Power.setFlat(True)
        self.pushButton_Power.setObjectName("pushButton_Power")
        self.pushButton_Restart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Restart.setGeometry(QtCore.QRect(480, 180, 300, 300))
        self.pushButton_Restart.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_Restart.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/pi/Desktop/New folder/MyGuiProjestCPE/GuiPythonCode/Image/restart_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Restart.setIcon(icon2)
        self.pushButton_Restart.setIconSize(QtCore.QSize(190, 190))
        self.pushButton_Restart.setFlat(True)
        self.pushButton_Restart.setObjectName("pushButton_Restart")
        OptionPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OptionPage)
        self.statusbar.setObjectName("statusbar")
        OptionPage.setStatusBar(self.statusbar)

        self.retranslateUi(OptionPage)
        QtCore.QMetaObject.connectSlotsByName(OptionPage)

    def retranslateUi(self, OptionPage):
        _translate = QtCore.QCoreApplication.translate
        OptionPage.setWindowTitle(_translate("OptionPage", "OptionPage"))
        self.pushButton_Undo.setText(_translate("OptionPage", "ย้อนกลับ"))
        self.label_Restart.setText(_translate("OptionPage", "รีบูตระบบ"))
        self.label_Power.setText(_translate("OptionPage", "ปิด"))
        self.label_ExitProgram.setText(_translate("OptionPage", "ออกโปรแกรม"))

        # Action Code

        # *-------ปุ่มปิดหน้า-------* #
        self.pushButton_Undo.clicked.connect(lambda :self.ExitundoOptionpage(OptionPage))

        # *----ปุ่มการทำงาน--------* #
        self.pushButton_Power.clicked.connect(self.Powerbtn)
        self.pushButton_Restart.clicked.connect(self.Restartbtn)
        self.pushButton_ExitProgram.clicked.connect(self.ExitProgrambtn)


    def ExitundoOptionpage(self, OptionPage):   #ออกจากหน้าต่างตั้งค่า
        OptionPage.close()

    def Powerbtn(self):     #ปิดเครื่อง
        print("Power !!!")
        #call("sudo poweroff", shell=True)

    def Restartbtn(self):   #ปิดและเปิดเครื่อว
        print("Restart !!!")
        #call("sudo reboot", shell=True)

    def ExitProgrambtn(self):   #ปิดโปรแกรม
        print("Exit !!!")
        exit()


"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionPage = QtWidgets.QMainWindow()
    ui = Ui_OptionPage()
    ui.setupUi(OptionPage)
    OptionPage.show()
    sys.exit(app.exec_())
"""
